### ISSUE TITLE
World Boss 3t3rmin4tion and Melvin won't allow tier 11

### ISSUE THREAD

**Issue by lyric911** [ilpersi/BHBot#121]
**Describe the bug**
When attempting either Melvin or 3t3rmin4tion, the error "2019-08-24 09:27:24,569 [MainThread] ERROR BHBotLogger - Invalid world boss tier for Melvin or 3xt3rmin4tion, must be equal to 10
2019-08-24 09:27:24,570 [MainThread] WARN BHBotLogger - Invalid world boss settings detected, World Boss will be skipped" is shown.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chromium
 - Version  v42

MainThread.Java, line 5326 changed to the below should fix this, I think?
if (worldBossTier >= 10 && worldBossTier <= 11) {

**Comment by ilpersi** [comment]
I pushed a fix and a new release for this: v42.1, you can get it from the release section. 😄 

Thank you for reporting. 👍
