### ISSUE TITLE
Enhancements for Pushover Notifications

### ISSUE THREAD

**Issue by lyric911** [ilpersi/BHBot#122]
**Is your feature request related to a problem? Please describe.**
No, just an enhancement.

**Describe the solution you'd like**
For the "i'm still alive" pushover notification, would it be possible to include success percentages in those notifications? Primarily concerned with WB, T/G, and Raids personally, but all activities could be configured.

Ideally, I'd like to see it say:

I'm alive and doing fine. Since the last notification, X raids have been attempted and Y were successful, for Z% success rate.

And repeat for the other activity types.

**Describe alternatives you've considered**
Reading the log files is the only other way I know to get a "health check".

**Additional context**
N/A

**Comment by lyric911** [comment]
I should have read all the open enhancements, there's a somewhat similar one #66 .

**Comment by ilpersi** [comment]
Yes, this is something I also would like to have.

As you can see from #66, to do things in the right way, we need some kind of persistence layer. I have some come for it and lately, with @Fortigate  we've been focusing on the [Steam port](https://github.com/ilpersi/BHBot/projects/1) so this feature is in standby at the moment.

We track raid success (for session duration only) and we can easily add that to the Pushover alive notifications. :)

**Comment by ilpersi** [comment]
Closing this as v42.8 is now able to track (for session duration only) success rates for all the performed dungeons and report it via Pushover.
