### ISSUE TITLE
Unable to raid 1 

### ISSUE THREAD

**Issue by Rawbrekt** [ilpersi/BHBot#124]
**Describe the bug**
Unable to raid 1 when it's the only one you have unlocked

**To Reproduce**
1. Only have raid 1 unlocked
2. Try to start a raid
3. Throws error "unable to find grey cue"

**Expected behavior**
Run raid 1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version 42.5

**Additional context**
I tried searching if any others had this issue and I found one closed issue.
It referred to another github that fixed it, but I don't see this being implemented here.

**Comment by ilpersi** [comment]
I am unable to reproduce this as I don't have an account with only R1 unlocked.

I packed a custom version for you that should fix the issue, can you try it and let me know? You can find it [here](https://drive.google.com/open?id=1iOM_yhmXgVVVNqa-ZbZOYURL_9HKApzJ).

**Comment by Rawbrekt** [comment]
Dude, you're a hero!
For some reason it got stuck on the completion windows in the first run.
All the other runs worked without issues!!
