### ISSUE TITLE
Raids considered complete before done, resulting in bot hanging

### ISSUE THREAD

**Issue by mental159** [ilpersi/BHBot#127]
**Describe the bug**
When running raids, the bot sometimes determines the raid is complete before it is. This is usually accompanied by the warning message "Error: unable to find 'x' button to close <activity> window. Ignoring". This is then followed with the info message "Weekly reward claimed successfully". When this happens, the bot generally times out and restarts.

**To Reproduce**
Happens randomly.  I seem to see it more frequently when running at high speeds At this time I was running at 31.25x speed.

**Expected behavior**
Raid to complete as expected.

**Screenshots**
Correct raid log flow.
![Correct raid flow](https://user-images.githubusercontent.com/52889830/66674530-bde10b00-ec28-11e9-95f7-f38d80281d1c.jpg)
Broken raid log flow.
![Broken raid flow](https://user-images.githubusercontent.com/52889830/66674537-c20d2880-ec28-11e9-8445-72d0ddc69435.jpg)
Sample of "weekly reward" from log.
![sample weekly reward window](https://user-images.githubusercontent.com/52889830/66674547-c6394600-ec28-11e9-8139-fbc5cdc75db2.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chromium
 - Version: 42.8

**Comment by Fortigate** [comment]
Should be fixed as of 99592f4df529a753a264392fbed2a328a3d74ea1, the bot was triggering the end of the activity from the "Victory" window when you defeat the raid boss, but you may have more mobs/chests in the raid. Now only the "Cleared" dialogue should trigger the end of a raid.

**Comment by ilpersi** [comment]
V42.9 is out with the fix so I am closing this. Should it happen again, fell free to open a new issue.
