### ISSUE TITLE
Bot are not connecting how should i do ?

### ISSUE THREAD

**Issue by 13December** [ilpersi/BHBot#128]
i'm only use a auto fishing

how can be use auto bot thank you 

for now i'm install Chromedriver v2.44 already and how doing next ??

i've try to run init file it just show in 1 second and disappear no nothing 

Thanks.

**Comment by Fortigate** [comment]
If you only want to use the fishing function you can download and use the fishing bot alone from [tiemonl's](https://github.com/tiemonl/Bit-Heroes-Fishing-Bot/tree/master/csharp) project.

If you want to run and set up the bot to automate Bitheroes follow the set up guide in the [wiki](https://github.com/ilpersi/BHBot/wiki).

**Comment by 13December** [comment]
BHBOT cant create file : META-INF\version\.9

is it normal ?

**Comment by ilpersi** [comment]
I reviewed the [initial setup documentation](https://github.com/ilpersi/BHBot/wiki): please be sure to doublecheck you followed all the steps.

**Comment by 13December** [comment]
i'm run the bot complete but cant see a log (no problem) cos i just raid when i'm sleep

Thanks.

**Comment by ilpersi** [comment]
So is the bot working fine for you now?

**Comment by 13December** [comment]
> 
> 
> So is the bot working fine for you now?

YEP new wiki is more understanding for set up 

Thanks
