### ISSUE TITLE
Speed question? Maybe speed detection/auto adjust

### ISSUE THREAD

**Issue by Hunteil** [ilpersi/BHBot#132]
**Is your feature request related to a problem? Please describe.**
Is speed supposed to be at x1.0? and no speed boots consumed? <-b/c by default these are set as this.

I'm thinking the bot can't detect things fast enough in battle to use a potion.... Just had a instance where I was in gauntlet and I died before it realized I needed a pot.

**Possible solution:**
Have the bot detect when at boss to slow down the speed.
Gauntlet it can just watch the numbers for which wave your on. 9 of 10 could start it.
Invasions to have it slow down after wave 20. <-maybe add setting to .ini
Then when the next area is started. It auto returns it to speed (2nd click)

**Addition content:**
I understand this would probably require some considerable work. So I understand if this has to go on the back burner. But a note about the speed should be added to the wiki steps.

**Comment by ilpersi** [comment]
I am not sure I understand the request. Do you mean to manually use a healing potion while the bot is running?

**Comment by Hunteil** [comment]
I mean the bot didn't use the potion automatically due to game moving so fast.

Or does it not automatically administer potions when a character dies?

**Comment by Fortigate** [comment]
You need to enable "Pause game on death" in game for auto potion to work, that's how the bot triggers the potion using.

**Comment by Hunteil** [comment]
Brilliant! <insert meme> My apologies.
