### ISSUE TITLE
dungeon/trial victory error

### ISSUE THREAD

**Issue by irissian** [ilpersi/BHBot#135]
**Describe the bug**
the bot thinks that it has won the dung/trial when its not yet finished then it doesn't detect the real victory message, to end up with an exception error

**To Reproduce**
1. Go to 'any dungeon/trial'
2. wait for it to randomly announce victory

**Expected behavior**
to not declare victory until "an actual" victory message is shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Version 42.9
![Untitled](https://user-images.githubusercontent.com/24226870/68996309-86edbd00-0898-11ea-9648-f4ced8a7f4ae.png)

**Comment by Fortigate** [comment]
Can you post the entire log / settings when this happens? I'm not seeing the same behaviour but I'm running the latest commits so it may be fixed in v43

**Comment by irissian** [comment]
[BHBot-2019-11-17-1.log](https://github.com/ilpersi/BHBot/files/3859448/BHBot-2019-11-17-1.log)
[settings.zip](https://github.com/ilpersi/BHBot/files/3859450/settings.zip)

**Comment by Fortigate** [comment]
As far as I know the error should have been benign, it was changed at some point to be a debug message rather than a warning. I just uploaded v43 which should have a fix for this issue, just reopen if it doesn't!
