### ISSUE TITLE
Disconnect has been detected/Raid prematurely ending

### ISSUE THREAD

**Issue by Facetless** [ilpersi/BHBot#136]
bot ending raid before actual raid is finished. Then disconnecting and having a 10 minute pause and then crash.
was running 42.9

Have done multiple fresh installs of Bhbot, oracle and chromium.

updated to v43.0 and am continuing to have similar problems it seems to be only with r7 using shard baskets. 
Ive swept the "closed" bug reports and cant find anything to help me.

Before this problem started happening Chromium would always pull itself to the front of my screen, now it will operate behind another window. not sure if  this is relevant.

if any of you wonderful people could help me i would be very grateful.

Im using windows 10 
chromium Version 69.0.3497.0

[settings.docx](https://github.com/ilpersi/BHBot/files/3883198/settings.docx)

[bhbot.log](https://github.com/ilpersi/BHBot/files/3883197/bhbot.log)

**Comment by Fortigate** [comment]
Thanks for the log file, it was super helpful! Looks like it stems from an issue with the 'Disconnected' dialog being found when it doesn't exist. Can you try this version and let me know if it fixes it?

[BHBot.zip](https://github.com/ilpersi/BHBot/files/3883365/BHBot.zip)

**Comment by Facetless** [comment]
running almost seamlessly! 
Thank you so much Fortigate!

Non serious issue for me is that I was getting "Victory run time: 31s. Average: 19s." in the middle of raid but it was not causing any issue to the opertation of the bot. Only seemed to happen within first 10 raids. 

ill just leave this here if you wanted to take a peek
[bhbot.log](https://github.com/ilpersi/BHBot/files/3883938/bhbot.log)

thanks for you help!
-A

**Comment by Fortigate** [comment]
I just had a look and there's a lot of legacy code that hasn't been touched since the project was revived a year ago in the dungeon process that's causing errors, I'll release 43.1 soon to hotfix both of these.

**Comment by Facetless** [comment]
Im not sure weather to post this on the close topic "trail/gauntlet completion" issue.

my bot really doesnt like to run trials, it usually freezes after 2 or 3 after telling me that the trail is complete 30 times.

[bhbot.log](https://github.com/ilpersi/BHBot/files/3908776/bhbot.log)

if and when you have time!
A

**Comment by Fortigate** [comment]
v30.1 with the dungeon code changes should fix all these issues, it has some core changes so we're making sure its stable before we release. Should be in a day or two!

**Comment by ilpersi** [comment]
@Facetless I've just released [v44pr1](https://github.com/ilpersi/BHBot/releases/tag/v44pr1) that contains many fixes and improvements: can you please check if you still have the issue?

**Comment by ilpersi** [comment]
@Facetless no feedback in two weeks, I am closing this. Feel free to open a new onw.
