### ISSUE TITLE
Expedition delay crash

### ISSUE THREAD

**Issue by thedamnbrownman** [ilpersi/BHBot#142]
Hello, 

Tried to do 1000 badges on expedition and The expedition will run 5-10 times and then it will not close out the final page to restart. It is consistent to where it will crash over and over. The idle time exceeded while state = main and then crash. 

thank you

**Comment by Fortigate** [comment]
Yup I'm having the same problem. When I rewrote the dungeon code Expedition wasn't active so I estimated the window closing routine which isn't very accurate. I'll put a fix in today.

**Comment by thedamnbrownman** [comment]
Youre awesome <3

**Comment by Fortigate** [comment]
Whoops, not sure how I closed the issue!

Can you try this build? Should fix it
[BHBot.zip](https://github.com/ilpersi/BHBot/files/4049342/BHBot.zip)

**Comment by ilpersi** [comment]
@thedamnbrownman does the fix provided by @Fortigate work for you?

**Comment by thedamnbrownman** [comment]
Hey brotha,

It did fix the issue. Thank you.

Sent from my iPhone

On Jan 31, 2020, at 10:37 AM, Lorenzo Persichetti <notifications@github.com> wrote:

﻿

@thedamnbrownman<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthedamnbrownman&data=02%7C01%7C%7Cf6eaf2b7ce5c4a52f09508d7a628cea2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637160566497720662&sdata=klXqXhlcgz8StbWvumt0YYu53IB0Wr6y6gIYHkYGtzk%3D&reserved=0> does the fix provided by @Fortigate<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFortigate&data=02%7C01%7C%7Cf6eaf2b7ce5c4a52f09508d7a628cea2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637160566497730672&sdata=t1AzT9ZfPmCiADYXQzqO5YNXqwCqqCkVTPOBFHS69N8%3D&reserved=0> work for you?

**Comment by ilpersi** [comment]
> It did fix the issue. Thank you.

I am closing this then. Feel free to open a new one if you still have issues. 😄
