### ISSUE TITLE
How to update BHBot?

### ISSUE THREAD

**Issue by E7t7t7** [ilpersi/BHBot#143]
when updating from 43 to 44 do I just drag the bh.jar into the folder and replace it?

**Comment by ilpersi** [comment]
You have to stop the bot before replacing the file. 👍

**Comment by E7t7t7** [comment]
> You have to stop the bot before replacing the file. 👍

Figured as much but was just making sure. <3

**Comment by Hunteil** [comment]
I forgot how to as well lol.

Basically:
1. Stop running bot (if running).
2. Download new version.
3. Copy and paste it into your bot folder and overwrite old jar.
4. Run bot.

If there's a problem.
5. Run init.bat and use install steps on wiki. (that's what I did just in case.)

btw I recommend cleaning out log folders or they could get very heavy.
Also adding "useDoNotShareURL 1" at the very end of the settings.ini file was an amazing addition guys. I can't recommend it enough. It allows 2 instances to run super smoothly on a old quad core PC that was on it's last leg. Now I think I can run 3-4 instances of the bot if I wanted. Not that I will. Just an example of how well it functions.

**Comment by ilpersi** [comment]
@Hunteil thank you for your contribution, I will probably re-use it in the wiki. 😄 
I was lazy being lazy about this issue. :p

**A bit more details on the log**
The log rotates every day. To manage how many days of logs you want to store, you can use the `logMaxDays` option in settings.ini

The default is 30: that means it will save the last 30 days of logs. Don't be fooled by the number of folders: once that you get the 30 days rolling, the old folders will remain but they will be empty.

In my experience running the bot with debug logs will create an average for 25KB of logs each day that means less than 1MB for each month. Do you see different statistics?

Please also note that you have the `logLevel` option to make the bot less verbose. :+1

**Comment by ilpersi** [comment]
As v45 the upgrade process is a bit different and somewhat documented in the Wiki, closing this.
