### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by eif0x** [ilpersi/BHBot#145]
after use ini.bat and set all the settings i use bhbot.bat and get this error. 

![error](https://user-images.githubusercontent.com/60366609/73213663-dda52c00-4150-11ea-9a09-abdc715b085d.png)

**Comment by dalatejc** [comment]
This is caused by an error in the settings file, if you attach a copy (make sure to remove any personal information) I can have a look. Otherwise type 'resetini' into the console to return the settings file to defaults and try and reconfigure.

**Comment by Fortigate** [comment]
This is caused by an error in the settings file, if you attach a copy (make sure to remove any personal information) I can have a look. Otherwise type 'resetini' into the console to return the settings file to defaults and try and reconfigure.

**Comment by eif0x** [comment]
with a fresh settings file it run fine but i cant find what i make wrong there are my setting:


# Enable/disable various activities
# (r=raids, d=dungeons, w=worldboss, t=trials, g=gauntlet, p=pvp, e=expedition, i=invasion, v=gvg, b=bounties, a=fishing baits collection, f=fishing)
# If both Dungeons and World Boss are enabled Dungeons will take priority
# To disable an activity, just remove the corresponding letter from the setting
# The bot will prioritise the activities from left to right while resources are available.
# E.G You can set Raids to lowest priority to ensure other resources don't cap while using shard baskets.
activitiesEnabled a t g p e v i w r b

# If round robin is enabled the bot will check the activities in order, in a repeating loop.
# This gives equal priority weighting to all activities.
activitiesRoundRobin 0

# Set maximum resources (For calculating values with guild perks)
maxShards 7
maxTokens 15
maxTickets 15
maxBadges 15

# Set minimum resources (Amount for the bot to leave for manual play)
minShards 1
minTokens 1
minEnergyPercentage 10
minTickets 1
minBadges 1

# Set resource cost of activities
costPVP 3
costGVG 5
costTrials 5
costGauntlet 5
costInvasion 5
costExpedition 5
baitAmount 1

# Trials/Gauntlet difficulty level
difficultyGauntlet 500
difficultyTrials 500

# Decrease difficulty when you lose
# format: <dungeon_type>:<levels_to_decrease>:[minimum_level]
# Only Expedition, Trials and Gauntlet supported, you can mix them as you want (e=expedition, t=trials, g=gauntlet)
# Example 'difficultyFailsafe t:1 g:5:100' -> you lose a trial, difficultyTrials is decreased by 1. you lose a gauntlet, difficultyGauntlet is decreased by 5 to a minimum level of 100
difficultyFailsafe t:5 g:5:100

# Increase difficulty after a given number of victories in a row
# format: <dungeon_type>:<required_victories_in_a_row>:<levels_to_increase>
# Only Trials and Gauntlet supported, you can mix them as you want (t=trials, g=gauntlet)
# Example 'successThreshold t:10:1 g:10:1' -> you win 10 trials in a row, difficultyTrials is increased by 1. You win 10 gauntlets in a row, difficultyGauntlet is increased by 1
successThreshold t:5:1 g:5:1

# PvP Opponent selection (select from the 1st to the 4th opponent in the PvP screen)
pvpOpponent 2

# GvG Opponent selection (select from the 1st to the 4th opponent in the GvG screen)
gvgOpponent 2

# World Boss Settings
# Format is 'worldBoss n 3 9'
# o=orlag, n=nether, m=melvin, 3=3xt3rmin4tion,  b=Brimstone Syndicate, t=Titans Attack followed by difficulty, then tier
worldBoss 3 1 11
# World Boss Timer (time to get a full lobby, on timeout return to main screen)
worldBossTimer 60
# If the lobby doesn't fill in time, run a dungeon instead? (0 = no, 1 = yes), useful for non peak hours
dungeonOnTimeout 1
# World Boss solo setting
worldBossSolo 0

# Auto-revive Settings (Auto-revive needs "Disable auto-pilot on death" setting to be enabled in game to work)
# format is autoRevive t g r e
# (t=trials, g=gauntlet, r=raid, e=expedition)
autoRevive t g r e
# Order to attempt to use revives (3 is 100% revive, 2 is 60%, 1 is 40%)
potionOrder 123
# Maximum potions to use per activity
potionLimit 5
# Enable this setting to use 100% revives on the tank position, as they tend to need them the most
# format is tankPriority t g r e
# (t=trials, g=gauntlet, r=raid, e=expedition)
tankPriority t g r e
# Tank position (5 is rear, 1 is front)
tankPosition 1

# Auto-shrine (automatically attempt to save shrines for trials/raid boss encounters.)
# format is autoShrine t r e
# (t=trials, r=raid, e=expedition)
autoShrine t r e
# Battle delay, this is the time with no encounters before enabling shrines.
battleDelay 30
# Shrine delay, this is the delay to traverse the map for shrines before enabling the boss
shrineDelay 20

# Auto-runes (automatically switch between minor runes depending on activity type).
# Rune types are "experience", "item_find", "capture" and "gold".
# When given a specific rune type for a rune slot, the highest grade rune of that type available for that slot will be
# chosen (e.g. when an "item_find" rune is specified, and a given slot has both an epic and a common item find rune
# equipped, the epic rune will always be preferred).
#
# Default rune set; this is the rune set loaded if not specified in the "autoRune" setting, below.
# Format is "autoRuneDefault <left rune type> [<right rune type>]"; if right rune is not defined, left rune will be
# used for both left and right slots.  If autoRuneDefault is not defined, autoRune and autoBossRune will be disabled.
#autoRuneDefault experience
#
# Auto-runes; use these runes when performing the specified activity.
# Format is "autoRune <activity> <left rune type> [<right rune type>]; <activity> ...".
# Activities are: d=dungeon, e=expedition, g=gauntlet, i=invasion, p=pvp, v=gvg, r=raid, t=trials, w=worldboss.
#autoRune g item_find; i item_find; w item_find
#
# Boss runes; use these runes when fighting a boss in one of the above activities (it will switch to the boss
# rune immediately before fighting the boss).  NB: This requires auto-shrines to be enabled.
# Format is "autoBossRune <activity> <left rune> [<right rune>]; <activity> ..."
#autoBossRune r item_find; e item_find; t item_find


# Dungeon solo threshold
# This zone and zones under it will be run solo to complete solo heroic bounties
minSolo 1

# Dungeons to run
# format is: z2d1 3 50;z2d4 50; first is zone/dungeon, second is difficulty and third is chance to run (z4's don't need difficulty defined)
dungeons z2d1 3 50; z3d1 3 50

# Dungeons/Raids to run on Wednesday (if you want to take advantage of capture day enter dungeons/raids here, else delete/comment out the lines)
#wednesdayDungeons z2d1 3 50; z3d1 3 50
#wednesdayRaids 1 3 100

# List of expeditions we want to do (there are 4 portals: p1, p2, p3 and p4) followed by the difficulty level and the chance to run
# Examples:
# 'p1 250 70;p2 230 30' ==> in 70% of cases it will do p1 at lvl 250, in 30% of cases it will do p2 at lvl 230
expeditions p1 10 25;p2 10 25;p3 10 25;p4 10 25

# Raids to run
# format is: 6 3 20;1 3 50; first is raid tier, second is difficulty level and the third is chance to run
raids 8 2 100

# PvP Stripping (You can unequip items to lower your TS to avoid high level players).
# Delete the line if you do not need it.
# fomat is: pvpstrip b r 
# (m=mainhand, o=offhand, b=body, r=ring, h=head, n=neck)
#pvpstrip o r
# same as pvpstrip, intented for GVG
#gvgstrip o r

# if autoconsume is 1 (enabled), then bot will automatically consume consumables defined by 'consumables' string
autoconsume 1

# the 'consumables' string defines consumables (separated by spaces) that should be always in use.
# Example: "consumables exp_minor item_major gold_average". This will make sure those 3 consumables are always in use.
# Possible consumable types are: exp_*, item_*, speed_* and gold_* (where * is minor, average or major).
consumables exp_minor speed_minor gold_minor item_minor

# Familiar encounter management based on type. Using this setting you can decide if you want to persuade/bribe encounters
# base on minimumb the level of the familiar. Possible values are 0 to do nothing, 1 to persuade/bribe starting from COMMON
# familiars, 2 to start from RARE, # 3 for EPIC, 4 for LEGENDARY.
# Exmple
# persuasionLevel 2 <- only familiars that are at least RARE will be persuaded
# bribeLevel 4 <- only LEGENDARY familiars will be automatically bribed.
# This parameter has the precedence over the familiars one

persuasionLevel 2
bribeLevel 4

# To get the list of all currently available familiars use the 'print familiars' command while the bot is running

# format is 'familiars squib 5; astaroth 1; violace 2'. familiar name first, amount you want to bribe second
# When a familiar is bribed this file will be automatically updated with the updated bribe counter
familiars ragnar 4; nosdoodoo 2; yeti 2; squib 2

# Misc settings
# Do you want BHBot to automatically start chromedriver for you?
autoStartChromeDriver 1
# Skeleton chest opening (0=decline all, 1=open all, 2=open in raid only)
openSkeletonChest 0

# Enable/disable various screenshots for logging
# (w=weekly rewards, d=daily rewards, a=fishing bait, b=bounties, dg=daily gems, wg=weekly gems, fe=familiar encounters, s=skeleton chest)
screenshots

# Development settings

# Saves a screenshot when encountering based on the type of the familiar
# 0 to do nothing, 1 to shoot starting from COMMON familiars, 2 from RARE, 3 from EPIC, 4 for LEGENDARY.
familiarScreenshot 1
# Do you want to contribute to familiar cue collecting? Setting this to 1 will upload cue of familiar names to a
# space where developers can use it to improve the detection. Please note that to keep your privacy safe only the
# portion of the screen containing the name of the familiar will be uploaded
contributeFamiliars 1

# BHBot log settings
# Where do you want to save the logs? (/logs/ by default)
logBaseDir logs
# What is the default level of the logs? There are different level available from debug to fatal. The debug level is
# extremely verbose and it is only recommended for developers
# debug, info, warn, error, fatal
logLevel info
# How many days of logs do we store?
logMaxDays 30

# Debug settings
debugDetectionTimes 0
hideWindowOnRestart 0
reconnectTimer 10


# This section of the setting is dedicated to the Pushover integration
# https://pushover.net/faq#overview-what
# Do you want to enable the Pushover integration?
enablePushover 0
# Pushover APP_TOKEN
poAppToken yourAppToken
# Pushover USER_TOKEN
poUserToken yourUserToken
# Do you want to be notified when BHbot crash?
poNotifyCrash 1
# Keep alive notification to be triggered every n hours
poNotifyAlive 6
# Do you want to be notified when BHbot finds unexpected errors?
poNotifyErrors 1
# Do you want to be notified when you receive a PM?
poNotifyPM 1
# Do you want to be notified of bribed familiars?
poNotifyBribe 1
# Do you want to be notified of special drops?
# (l for legendary, s for set, m for mythical)
poNotifyDrop l s e

**Comment by ilpersi** [comment]
If you do not want to have periodic screenshots please just comment out the `screenshots` option. Leaving it with no values as you did will cause this issue.

**Comment by eif0x** [comment]
thx!

**Comment by ilpersi** [comment]
In future similars errors won't trigger a Java errot,, but will make the bot stop with a more descriptive message.

Thank you for the contribution.
