### ISSUE TITLE
How do i get fishing to run with the bot?

### ISSUE THREAD

**Issue by E7t7t7** [ilpersi/BHBot#146]
The bot will run the fishing portion and it will run to the platform to open up the fishing thing. Will then say "pausing for 25s to fish" do nothing < unpause and continue on with the loop.

I think you mentioned an issue with chrome before but it just seems odd for everything else to work properly but this one aspect.

```
# Enable/disable various activities
# (r=raids, d=dungeons, w=worldboss, t=trials, g=gauntlet, p=pvp, e=expedition, i=invasion, v=gvg, b=bounties, a=fishing baits collection, f=fishing)
# If both Dungeons and World Boss are enabled Dungeons will take priority
# To disable an activity, just remove the corresponding letter from the setting
# The bot will prioritise the activities from left to right while resources are available.
# E.G You can set Raids to lowest priority to ensure other resources don't cap while using shard baskets.
activitiesEnabled a r e d g t p b f
```

**Comment by ilpersi** [comment]
Did you have a look at the [article in the wiki](https://github.com/ilpersi/BHBot/wiki/Fishing)?

**Comment by E7t7t7** [comment]
> Did you have a look at the article in the wiki?

indeed I did. it still just pauses the bot resumes and doesn't fish

**Comment by E7t7t7** [comment]
ill try once again could of been a bug who knows

**Comment by E7t7t7** [comment]
I will confirm in 15.3 hours when bait resets

**Comment by E7t7t7** [comment]
it doesn't work with the same efficiency as if you just ran it solo but it does in deed work as you described
