### ISSUE TITLE
How to Bribe specific familiars?

### ISSUE THREAD

**Issue by E7t7t7** [ilpersi/BHBot#147]
So the setting allows you to bring beyond a certain point like ONLY legend or whatever you wish but if you can add the ability for specific bribes aswell like it will bribe ONLY legend but it will also buy user specified whatever.

**Comment by ilpersi** [comment]
I am not sure I get this and I think that what you're asking is already there.

```
# format is 'familiars squib 5; astaroth 1; violace 2'. familiar name first, amount you want to bribe second
# When a familiar is bribed this file will be automatically updated with the updated bribe counter
familiars squib 1
```

To know the available familiars issue a `print familiars` command in the console

**Comment by E7t7t7** [comment]
so if I have it set to only bribe legendaries but lets say put "Yeti 3" then it will capture the yeti anyway?

**Comment by ilpersi** [comment]
Yep.

I don't remember if it is case sensitive so be sure put everything in lower case `yeti 3` and if you want to be 100% safe just copy paste the name from the `print familiars` command.

**Comment by E7t7t7** [comment]
If I want it to ignore a specific familier to I put like squibb 0

**Comment by ilpersi** [comment]
There is no ignore functionality. The bot will check, in order:
- is the encounter level the same or higher than `bribeLevel` setting?
- is the current encounter part of the `familiars` setting?

If any of the conditions is true, the encounter will be bribed.

The setting automatically goes to zero after all the encounters you specified have been bribed. When the setting is at zero the `bribeLevel` config is applied. Hope this is clear.
