### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by rafaelcmm** [ilpersi/BHBot#148]
**Describe the bug**
My bot does not work properly. It opens the config window and just display errors. After a while, it throws an NPE and restarts.

**To Reproduce**
1. Install
2. run BHBot.bat

**Screenshots**

![err1](https://user-images.githubusercontent.com/24925712/73844562-8f9ec100-47ff-11ea-8834-14489d0496aa.png)
![err2](https://user-images.githubusercontent.com/24925712/73844567-90375780-47ff-11ea-8f73-38198a1f4396.png)

**Settings**
Please attach a copy of your settings.ini file. Make sure to remove personal/sensitive information

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chromium
 - Version 44

**Comment by Fortigate** [comment]
Does the bot open any windows in the game, or just throw errors in the console?

**Comment by rafaelcmm** [comment]
It opens the window normally, then opens the config screen and nothing more

Em qua, 5 de fev de 2020 10:23, Fortigate <notifications@github.com>
escreveu:

**Comment by Fortigate** [comment]
Can you check the screenshot folder and see if any error screenshots are being saved?

**Comment by ilpersi** [comment]
@rafaelcmm is there any update on this?

**Comment by ilpersi** [comment]
No feedback in more than a week. Closing this, if required, feel free to open a new one.
