### ISSUE TITLE
Bot causing chromium window to take focus

### ISSUE THREAD

**Issue by mental159** [ilpersi/BHBot#149]
**Describe the bug**
It seems recently when the bot is running the chromium window takes focus, regardless of whether it is hidden or not. I believe this started with the last version.

I used to be able to run the bot in the background and do other things on my system. However, now it is impossible as the focus gets pulled to the chromium window every few seconds and any typing starts to get added to the front of the url. Hitting enter then obviously changes the site and causes the bot to crash.

**To Reproduce**

    Install
    run BHBot.bat

**Desktop (please complete the following information):**

    OS: windows 10
    Browser Chromium
    Version 44

**Comment by ilpersi** [comment]
We did not change anything in how the browser is managed. What you see is more or less the expected behavior and it is not possible to change it as the browser interaction is managed by a dedicated library not developed by us.

Did you have the chance to review the documentation on the Home Page? I am pasting it here.

> ## Important
> 
> - While bot is running, do not interfere with the Chromium window that the bot has open via chromedriver. That means don't open menus and click around since that may confuse the bot and it could fail to do its tasks (which could lead to crashing it).
> - If you want to continue using your computer while running the bot use, the 'hide' command to minimize the window. The bot clicks on certain buttons and cues and expects certain thing to pop up, and if they don't (due to user interaction), then it will fail to function properly. 
> - If you are running the bot in Windows, you may want to run it under a separate account in order for it to not interfere with your work.

**Comment by D3mi-God** [comment]
I had the same issue and has recently found a solution for it:
https://stackoverflow.com/questions/46035014/how-can-it-be-possible-to-steal-focus-so-easily
Basically you need to change ForegroundLockTimeout back to its default value (200000 in decimal or 30d40 in hexa) in the registry HKCU\Control Panel\Desktop.
Hope it helps

**Comment by mental159** [comment]
It was set to 200000 already, but changing the setting to a slightly larger
number and saving seems to have corrected the issue. Thanks!
