### ISSUE TITLE
Wiped Settings

### ISSUE THREAD

**Issue by E7t7t7** [ilpersi/BHBot#151]
Bot was running fine all day started bugging out about an hour ago turns out my setting file was wiped entirely. I really don't have more details than this s im aware if this issue isn't already known there prob isn't much that can be done but just wonderin

**Comment by Fortigate** [comment]
Do you have the log files from when this happened? There is a small chance that while the settings.ini file is being updated by the bot that the file can become corrupted and wiped, but I've never seen it before.

**Comment by E7t7t7** [comment]
> Do you have the log files from when this happened? There is a small chance that while the settings.ini file is being updated by the bot that the file can become corrupted and wiped, but I've never seen it before.

I mean I could pull up the logs from those days but I couldn't tell you exactly when it occurred as I was at work I just put in another settings file I had and havnt had issues. ima chalk it up to shit happens if you want the days logs ill send it but idk what time.
