### ISSUE TITLE
Stuck at GVG end screen

### ISSUE THREAD

**Issue by E7t7t7** [ilpersi/BHBot#152]
![Windows 10 x64 - VMware Workstation 15 Player (Non-commercial use only) 2_28_2020 6_28_29 AM](https://user-images.githubusercontent.com/14986593/75545210-b2358b80-59f3-11ea-8b72-7bbe0b70e4fe.png)
ran bot as norm and gets stuck in gvg end screen ss of area its stuck at included

**Comment by ilpersi** [comment]
This should be fixed in 126f1ef117a9db12f620df7ec828daa7ffe42576. I am currently testing it.

**Comment by thedamnbrownman** [comment]
Same for me. Updated and still stuck at victory screen. =]

**Comment by bluewolf0595** [comment]
Same issue. Also don't know how to apply that fix to try it out.

**Comment by ilpersi** [comment]
You can compile from source or wait for us to release a new version.

Please keep in mind that after 15 minutes of idle time, the bot will restart itself so it is not a big issue.

**Comment by guera-surena** [comment]
> You can compile from source or wait for us to release a new version.
> 
> Please keep in mind that after 15 minutes of idle time, the bot will restart itself so it is not a big issue.
The 15 minute reset is inefficient when grinding only GvG. I'm working on integrating the fix... Java certainly has changed since the late 90s early 2000s. lol

**Comment by Fortigate** [comment]
Here's the latest commits compiled. This fixes the Victory screen hanging, but still freezes at Defeat, once that's fixed I'll push a proper release.

[BHBot.zip](https://github.com/ilpersi/BHBot/files/4271736/BHBot.zip)

**Comment by guera-surena** [comment]
you rock! thanks
> Here's the latest commits compiled. This fixes the Victory screen hanging, but still freezes at Defeat, once that's fixed I'll push a proper release.
> 
> [BHBot.zip](https://github.com/ilpersi/BHBot/files/4271736/BHBot.zip)

**Comment by E7t7t7** [comment]
testing now.

**Comment by Fortigate** [comment]
Both should be fixed as of b26fa6c7f9aa3b6311d57d536830a1c33f6d10e5.  New release will be coming soon with these included. Closing for now
