### ISSUE TITLE
pop up cue not detected

### ISSUE THREAD

**Issue by DieNastie** [ilpersi/BHBot#154]
reopening issue #150

same problem as described
expedition, gauntlet and invasion get stuck at random
sometimes they work sometimes they dont
bot does resume if you manually close both pop ups

additionally invasion sometimes doesnt even start, getting stuck on the accept pop up
also the screen aka the game keeps jittering up and down by like one or two pixels
fixed by a restart but it comes back fairly quick

Setup:
 - Win10 64x
 - Chromium from the installation guide
 - resolution 1300x750 or something like that
 - DPI 100%

[settings.txt](https://github.com/ilpersi/BHBot/files/4381305/settings.txt)

![Pop up cue not detected](https://user-images.githubusercontent.com/36104129/77544505-5e5e7b00-6ea9-11ea-95ad-b9b0b4861fb9.png)

**Comment by DieNastie** [comment]
now the bot thinks its winning every gauntlet in 0 seconds

![pop up cue UPDATE](https://user-images.githubusercontent.com/36104129/77814402-02fed980-70b1-11ea-80b1-09c49e965505.png)

**Comment by ilpersi** [comment]
Can you please confirm that you are using the latest release (v44.1) and you applied the recommended settings?

**Comment by DieNastie** [comment]
print version is in the 1st screenshot

which recommended settings? just try use default?

**Comment by ilpersi** [comment]
I mean the game settings described in the wiki: https://github.com/ilpersi/BHBot/wiki

**Comment by DieNastie** [comment]
i set all settings during installation aside from battle text and bars

after one full test of recources it runs fine
im gonna assume the one time expedition failling to start was just a fluke
its still being jittery tho
does that even mean anything?

tl:dr: im an idiot

**Comment by ilpersi** [comment]
Can you qualify "jittery"? 😄 
Is it working or do you still have issues?

BTW: installation instructions were not so detailed, so they changed over time (hoping to make them better): it may be possible that when you did the first configuration they were a bit different.

**Comment by DieNastie** [comment]
aside from bait claiming it seems to be working so far

![2020-03-30 09_26_34-MSIX on 127 0 0 1 - Virtual Machine Connection](https://user-images.githubusercontent.com/36104129/77886322-f1f8c880-7268-11ea-8d6f-8128a0dd3fc6.png)

![2020-03-30 09_27_13-MSIX on 127 0 0 1 - Virtual Machine Connection](https://user-images.githubusercontent.com/36104129/77886333-f6bd7c80-7268-11ea-8e64-209617e80906.png)

as described its that one pixel moving up and down very quickly
a pain to even try get a screenshot but i managed
the scroll bar itself does not seem to be moving

**Comment by ilpersi** [comment]
The screen stuttering is a won't fix known glitch. :)
In the end you're not supposed to watch the bot while it is running so that should not bother you.

If you really can't live with it, you can add a `useDoNotShareURL 1` line to your `settings.ini`. This is an experimental settings that will make the bot get rid of the Kongregate interface. This also solves the screen muttering.

**Comment by ilpersi** [comment]
@DieNastie I assume you have no issues so if I don't get any feedback in the upcoming 24 hours I am going to close this.

**Comment by DieNastie** [comment]
which would you say runs more stable? with or without DoNotShareURL?

im just concorned about stability cus i mainly run the bot before going to bed

**Comment by ilpersi** [comment]
I only run with `useDoNotShareURL 1` and I can leave the bot to go unattended for weeks (currently my record is 10 days in a row).

**Comment by DieNastie** [comment]
then there must be something else on my end tho i cant pin it down yet

let me test around for a few days
i can close this myself cant i?

**Comment by ilpersi** [comment]
Are you running the bot on a VM? If yes what is the setup (RAM, CPU, Disk)

We can wait to close this as much we want. I usually close only when there is no feedback for a while (like a week) to avoid stale issues.

**Comment by DieNastie** [comment]
using hyper v
i used a preset for now to try the bot out

105gig Disk
CPU for VM is uncapped ( i7 )
RAM is dynamic between 512MB and what looks like 1 terabyte   oO

**Comment by ilpersi** [comment]
I'm not so expert on Hyper-V. I would say you have plenty of resources.

My current setup is this:

- 2 Core vCPU
- 4GB RAM
- 40GB SSD STORAGE

I am renting it from [here](https://iportal.host/aff.php?aff=187). Maybe this can work also for you.

**Comment by DieNastie** [comment]
ok i redid my VM
less storage but 4gigs of static RAM
that looks like ironed out most issues aside from one
invasion fails to start
![2020-04-04 16_13_29-BH on DESKTOP - Virtual Machine Connection](https://user-images.githubusercontent.com/36104129/78453120-06392d00-7690-11ea-8e6f-8c4415650a45.png)
i AM seeing a pattern tho
it only fails if the VM window is actually open
if i just tab out before the game gets to the invasion screen then it works

**Comment by ilpersi** [comment]
Have a look at #139, a similar issue has been reported and I provided a custom build for that. Try to check if that helps.

**Comment by ilpersi** [comment]
@DieNastie JFYI: [this](https://github.com/ilpersi/BHBot/issues/139#issuecomment-602273856) is where I provide the custom build.

**Comment by DieNastie** [comment]
ran one invasion fine then hung itself on the 2nd

**Comment by ilpersi** [comment]
New day, [new build](https://drive.google.com/u/0/uc?id=1Vtv2DZ44lxslnzEPoT_-dit_8MlW9jUV&export=download), hope this time is the right one. 😄

**Comment by DieNastie** [comment]
are you pulling these out of a hat? whats different? just the speed?

also im starting to think this is a hardware issue
bot runs with the exact same issue on pc as on vm

**Comment by ilpersi** [comment]
I did not increase the time, I just added a check for the position of the Accept button.

Sometimes, if the check is not there, the bot can try to click the button while the invasion dialog is sliding down so it clicks in the wrong position. Most of the buttons have this check, I don't know why the Invasion did not (that part of the code is pretty legacy).

Based on your feedback it looks like it something that has to do with graphics. With Hyper V do you have the possibility to tweak the graphic memory? Maybe increasing it a bit should give better performance. These are just my assumptions based on the few elements I have. 😄

**Comment by DieNastie** [comment]
the issue happens if i run it on my pc too
we are talking about a NVIDIA RTX 206 SUPER

**Comment by ilpersi** [comment]
Nope, then it is not the graphic card. Is it still happening also with the last build?

**Comment by DieNastie** [comment]
i was gonna run 20 more to see how many it manages before i reply
but so far 10 more got done and no issue

**Comment by DieNastie** [comment]
lets wait a bit
you never know

**Comment by DieNastie** [comment]
how high is the chance for some sort of hick up to happen?
like the bot hanging itself or crashing? is once a day avarage?

also ive got one minor bug to report and 2 suggestions to make
should i open new posts for that?

**Comment by ilpersi** [comment]
The bot will crash every now and then and notify you (if you enabled notifications) this is supposed to be so: the important point is that the bot is able to restart itself when a crash occurs and you don't lose resources.

I also have some crashes cause Kong is changing graphics quite frequently so it is hard to always be up to date. It is a trade-off you have to leave with 😄:  the bot can run while I sleep and otherwise you'd have to grind manually, so even if a few crash happens you still save a lot of time (and also save your wrist).

Please keep things separated: one bug one issue, one suggestion one issue. In this way, each topic has its own thread and it can also have dedicated commits in code.

As the bug in this thread is solved I will remove the bug tag.
