### ISSUE TITLE
round robin with fishing

### ISSUE THREAD

**Issue by DieNastie** [ilpersi/BHBot#155]
this is a minor thing that occurs when i use fishing in my settings with round robin turned on
the bot after fishing one bait for no explicable reason goes to the guild hall
doesnt usually disturb the bots functionality but i guess at least going over that part of the code might not hurt

**Comment by ilpersi** [comment]
This is the intended behavior.

The original idea was to port you back to the guild to avoid friend requests and other interactions. I do agree that not everybody is willing to do so and in this regard, I will add an option to the mini file to manage the behavior

**Comment by DieNastie** [comment]
wait how old is that code then? before BH had the deny friend requests option?

**Comment by Fortigate** [comment]
Fairly recent, I added it as I didn't like idling on the fishing island, and don't want to turn friend requests off. I would have added a toggle but I didn't think anyone else used this feature.

**Comment by ilpersi** [comment]
v45 is out with the new `enterGuildHall` dedicated setting for guild porting after fishing is over.
