### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Playstoreman** [ilpersi/BHBot#157]
Hi, I don't really understand how to modify the settings.ini because when i try to change some parameters the bot didn't do Quest or Raid.

Could i get a nice settings.ini from a player that use it frequently ?

**Comment by ilpersi** [comment]
**General advice**
While I could provide my `settings.ini`, I don't think this would solve your issues as it is highly customized for my needs.

My recommendation is that you start with the default `settings.ini`: it is a nice one and it has raids enabled. If you also want to enable dungeons starting from it you should replace the `w` with a `d` in the `activitiesEnabled` setting row.

The line should look like this:
`activitiesEnabled a t g p e v i d r b`

**Some more suggestions**
If you want to reset the `settings.ini` to the default you have to use the `resetini` command in the bot console.

Last but not least: I recommend you to review the [installation steps](https://github.com/ilpersi/BHBot/wiki#steps) and **make sure to run** `init.bat` **just once and after that use** `bhbot.bat`.

**Comment by Playstoreman** [comment]
Ok, thx for your help now the bot do the Dungeons.

I got an other issue when the bot is running sometime he stop to activate/desactive "auto shrine" or "ignore boss" in the options, that take a lot of time in all Raids/Dungeons. How to stop this parameter ?

**Comment by ilpersi** [comment]
That one is a feature that makes it so to save shrines for boss encounter.

To tweak it, there is a dedicated section in the `settings.ini`

> ```
> # Auto-shrine (automatically attempt to save shrines for trials/raid boss encounters.)
> # format is autoShrine t r e
> # (t=trials, r=raid, e=expedition)
> autoShrine t r e
> # Battle delay, this is the time with no encounters before enabling shrines.
> battleDelay 30
> # Shrine delay, this is the delay to traverse the map for shrines before enabling the boss
> shrineDelay 20
> ```

**Comment by ilpersi** [comment]
@Playstoreman I am closing this as I've got no feedback in the last 10 days, feel free to open a new one if you need more advice.
