### ISSUE TITLE
Question: Settings order

### ISSUE THREAD

**Issue by Hunteil** [ilpersi/BHBot#158]
Just a question oh mighty and wise one :-) :
In the Settings.ini
Can sections be reordered without anything going wrong?

i.e.

'# Text example1
'# Test example1 more text

'# Text example2
'# Test example2 more text

Then move example 2 in front of 1. (b/c it's easier to find a topic you change often)
ps: had to add ' to stop formatting here

**Comment by Hunteil** [comment]
If not then I can add this as a request to move these various items as I think it would be useful grouping in this order. (Currently there's a lot of hunting for and picking and often I forget to check a setting elsewhere b/c it's no where near it.)
i.e.

Place these under: Set resource cost of activities
Dungeon solo threshold
Dungeons to run
Raids to run
Dungeon/Raids to run Thursday
World Boss settings
Expedition settings
Trails/Gauntlet
Decrease difficulty when you lose (settings)
PvP
GvG
PvP stripping
World Boss Settings

then
auto-consume (move here b/c this is edited often)
auto-revive
auto-shrine
auto-rune etc etc etc (everything below is fine)

**Comment by Hunteil** [comment]
by pull request... do you mean pull it myself and edit or just make a suggestion?

PS: I went and edited my template. Looks way better now. :-) ty

**Comment by Hunteil** [comment]
I think I understand. I'm uploading now.... err I made a fork...
Not sure if I did this right sorry. Never used github to edit anything before.

https://github.com/Hunteil/BHBot/commit/8351929a5de2701792389fcbe712d7869a39683b

**Comment by ilpersi** [comment]
This is quite interesting as I also don't like the current setting.ini system.

What we have is a very old legacy from when the bot has been originally created by Betalord and I never changed it as, even if a bit messy, it works quite well and it is really easy to maintain (if you want to add a new setting, it takes minutes to do it).

Ideally speaking, if you could create a system from scratch, what would you like to have to manage configurations? :)

**Comment by Hunteil** [comment]
I'm actually fine with the ini system as I've used ini files before to adjust background settings in other professional applications and games. Just wish I can bold and make things easier to see without adding extra accidental code that could mess up the host program.

But I'm also fine with a dialog box to fill out my settings. Something with multiple tabs like the first tab is general settings. 2nd tab basic dungeons/raids/gauntlet/trail/expeditions etc etc. The 3rd would be auto functions like auto-consumables etc... last would be the left over stuff I've never had need to touch. And the nice thing about these is you can't mess them up as a user by accident. And settings you need will always be displayed (no hidden settings like my useDoNotShareURL). You can also set this up as a launcher of some sort. But I'm not sure how hard all of that is to setup and edit/update overtime.

Speaking of that dialog box... I can see that being a stand alone UI mini program that just edits the ini file for the users. Just a easier interface for those who need to edit it often.

PS: if you do this... make sure you can point the program ini in focus... So those who are using the bot in more than 1 instance can edit for each. Also there would be a save/update ini button and a launch button if your doing that.

**Comment by ilpersi** [comment]
If you ask @Fortigate he will tell you that having a launcher is something I would like to since at least one year 😄 

It would mean a lot of work/time and honestly, considering this is a free tool, for the moment I gave up.
