### ISSUE TITLE
Webhook discord

### ISSUE THREAD

**Issue by grums67** [ilpersi/BHBot#160]
Hello
Can you explain to me how to use Discord for notifications?
  Thank you

**Comment by ilpersi** [comment]
Discord functionality is not currently released: it will be available in the next release together with the documentation.

**Comment by grums67** [comment]
Ok great thank you
If you need people to test there is no problem

**Comment by ilpersi** [comment]
v45 is out with Discord support and documentation is in the Wiki. 👍
