### ISSUE TITLE
Fishing bot bugs

### ISSUE THREAD

**Issue by Hunteil** [ilpersi/BHBot#161]
**Describe the bug**
So the fishing bot keeps messing up... it'll randomly forget to move the mouse away from from the Start, Cast, Catch, Trade button (which changes color based on mouse placement). This in turn will cause the bot to hang waiting for the button to appear. If you miss the catch during this. It'll hang forever in the It got away! dialog box... if this sits forever like this... the main bot will re-awaken and restart the bot... unless the user manually closes the It got away! box and does something else... Then the fishing bot will still be waiting in the back ground until you click fishing and try to catch something again and it'll start again... (I know this b/c I accidentally discovered this.) If this is allowed to happen (worst case scenario)... we maybe using a few instances of the fishing bot while the normal bot is working and tieing up resources.

As far as the bot itself hanging for that button...if you manually close the it got away box... make sure you return the game to the capture button and it'll re-continue.

**Things to consider**
I thought first it was b/c of my wireless mouse was shutting off and sending a signal messing it up. But I manually turned it off and watched and it just kept happening. And I would have to turn it back on and correct it's mouse placement.

After fixing the placement of my mouse for the bot a few dozen times, it started operating perfectly for 5 minutes. So maybe something is going on in the background of the PC that's slowing it down or something?

**Solution**
Add a few more safe guard steps to ensure the mouse pointer is away or include the button images being depressed as targets too.

**Comment by ilpersi** [comment]
The ability to use fishing bait is available thanks to the [Bit-Heroes-Fishing-Bot](https://github.com/tiemonl/Bit-Heroes-Fishing-Bot) by [tiemonl](https://github.com/tiemonl) and it is not something we maintain or develop.

I do appreciate the feedback and the best option would probably be to address to tiemonl the issues you're having.

**Comment by Hunteil** [comment]
copied to here: https://github.com/tiemonl/Bit-Heroes-Fishing-Bot/issues/48
