### ISSUE TITLE
Issue with solo world boss

### ISSUE THREAD

**Issue by dotdeas** [ilpersi/BHBot#162]
Hi,

It seems like the bot crashes when running solo world boss and energy is lower then required. Tried it multiple times but same issue every time.

Running windows 10 with latest release of the bot.

> 2020-05-15 10:06:42,846 [DungeonThread] READOUT com.github.ilpersi.BHBot.BHBotLogger - Energy: 1%, required: >0%
> 
> 2020-05-15 10:06:43,619 [DungeonThread] INFO com.github.ilpersi.BHBot.BHBotLogger - Attempting Normal T11 Melvin Solo
> 
> 2020-05-15 10:07:25,168 [DungeonThread] WARN com.github.ilpersi.BHBot.BHBotLogger - Problem detected: insufficient energy to attempt WorldBoss. Cancelling...
> 
> 2020-05-15 10:07:41,878 [DungeonThread] ERROR com.github.ilpersi.BHBot.BHBotLogger - Error: unable to close popup <AutoTeam> securely: popup cue not detected!
> 
> 2020-05-15 10:07:57,249 [DungeonThread] ERROR com.github.ilpersi.BHBot.BHBotLogger - Error: unable to close popup <Normal> securely: popup cue not detected!
> 
> 2020-05-15 10:08:11,936 [DungeonThread] ERROR com.github.ilpersi.BHBot.BHBotLogger - Error: unable to close popup <ZonesButton> securely: popup cue not detected!
> 
> 2020-05-15 10:21:43,574 [DungeonThread] WARN com.github.ilpersi.BHBot.BHBotLogger - Idle time exceeded... perhaps caught in a loop? Restarting... (state=Main)
> 
> 2020-05-15 10:21:44,149 [DungeonThread] WARN com.github.ilpersi.BHBot.BHBotLogger - Doing driver emergency restart...

**Comment by ilpersi** [comment]
I'll have a look. You have a workaround tough that is to increase the minimum energy percentage so that the bot will not try to start a WB.
