### ISSUE TITLE
bh bot exe won't run

### ISSUE THREAD

**Issue by wachoo12** [ilpersi/BHBot#165]
hello ilpersi, i had an older version of the bot befor u had the exe. when i got a new computer i got the new version of bh bot but when i run the exe it gets grayed out and wont work. hope u help, wachoo12.

**Comment by ilpersi** [comment]
Hi,
I really have no elements here to help you: no logs, no screenshot only some very high-level description so it is quite hard for me to provide any kind of help.

What I suggest you do is to perform a new installation from scratch following the [Simplified Steps](https://github.com/ilpersi/BHBot/wiki#simplified-steps) in the wiki. I also recommend you:

- to create a new dedicated folder in the root of you drive (like `C:\BHBot`) to avoid any permission issue
- your anti-virus is not messing with BHBot

**Comment by ilpersi** [comment]
No feedback for more than 10 days, I am closing this. If you need feel to open a new one.
