### ISSUE TITLE
Updating familiar management system

### ISSUE THREAD

**Issue by MugenEnzan** [ilpersi/BHBot#166]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Update the bot to recognize all familiars up to T13

**Describe alternatives you've considered**
None

**Additional context**
None

I can sponsor this effort since its quite large. Let us get in touch to discuss this.

**Comment by ilpersi** [comment]
The latest commit I've just pushed includes a total of 26 new familiars including some (if not all) from T13. If you think something is missing get in touch with me.

Feel free to make a donation if you like so.

**Comment by MugenEnzan** [comment]
Huh! Perhaps I misread the print familiars output, I could've sworn a lot were missing!

So if I understand this correctly, all familiars available in the game that can be persuaded or bribed are supported, yeah?

Expect a paypal dontation :D

**Comment by ilpersi** [comment]
I've added them to the source code, but they are not in the latest release. Do you know ho to compile the code?

**Comment by ilpersi** [comment]
This is part of v45.2
