### ISSUE TITLE
Speed Kicks consumption

### ISSUE THREAD

**Issue by DieNastie** [ilpersi/BHBot#167]
since the new update the bot keeps using a speed kicks whenever i first start the bot or it crashes
yes even if there is still duration left on the buff

does the new add watching icon have to do with this?

**Comment by ilpersi** [comment]
I noticed that as well, it is the new add watching icon that makes the kick icon go behind the shop one.

I'll have a look and a workaround I suggest to disable speed kicks from autoconsume options.

**Comment by ilpersi** [comment]
V45.2 containing the fix is out, check it out.
