### ISSUE TITLE
Raid 1 (Astaroth) Crashes

### ISSUE THREAD

**Issue by MugenEnzan** [ilpersi/BHBot#168]
**Describe the bug**
Whenever I try to run raid 1, the bot errors out saying "Impossible to detect the currently selected grey cue " (???)

**To Reproduce**
1. Set the bot up for r 1
2. Run bot
3. Immediate crash and restart

I tried it with several settings files, even known-working ones, as well as a brand new one generated by BHBot.exe from a new download in a new location.

**Expected behavior**
It should run raid 1

**Screenshots**
https://i.imgur.com/MVxh8to.png

**Settings**
Please attach a copy of your settings.ini file. Make sure to remove personal/sensitive information
I uploaded the "clean" settings.ini, only changed fams to bribe and what raid to run.
[settings.zip](https://github.com/ilpersi/BHBot/files/4775271/settings.zip)
Had to zip it because of GitHub.

**Desktop (please complete the following information):**
 - OS: Linux with Win 10 VM
 - Browser: Chromium bundled with BHBot
 - Version: Latest

**Additional context**
None

**Comment by MugenEnzan** [comment]
Nvm, go ahead and close this if you want. 
I decide to try a fresh installation of BHBot and it worked.

Something must be borked in my own config...

Sorry for the trouble!

**Comment by MugenEnzan** [comment]
Aaaaaand its back after restarting the bot and using a new settings.ini...

**Comment by MugenEnzan** [comment]
Ran a few more tests and it happens on all raids

**Comment by ilpersi** [comment]
When the bot crashes, in the `/screenshots` folder a screenshot of the game is created. Can you please attach that?

Be sure to hide personal details.

**Comment by MugenEnzan** [comment]
[errors.zip](https://github.com/ilpersi/BHBot/files/4784944/errors.zip)
Here it is! There were no details I could see in the image or the log.

**Comment by ilpersi** [comment]
I fixed this in the last commit. The issue only happens when R1 is currently selected.

**Comment by ilpersi** [comment]
V45.2 containing the fix is out, check it out.

**Comment by MugenEnzan** [comment]
Confirmed working for all raids.
Thanks!!!!
