### ISSUE TITLE
Crash after pausing and scrolling

### ISSUE THREAD

**Issue by mikeoeo** [ilpersi/BHBot#178]
**Describe the bug**
Bot encountered a `RasterFormatException: y lies outside the raster` and closed the Chromium window while I was doing a pvp battle because I accidentally scrolled the window, even though the bot should be on pause.

**To Reproduce**
1. Start bot
2. After the game opens run command `pause`
3. Scroll the window

**Expected behavior**
Before v46 during pause the bot didn't do anything, now it stills does sth in the background.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium
 - Version: 69.0.3497.0 (64-bit)

**bhbot.log**
[bhbot.log](https://github.com/ilpersi/BHBot/files/5002134/bhbot.log)

**Comment by ilpersi** [comment]
Nothing has changed from v45.2 to v46 regarding pause management and it expected that the pause command is not immediate (depends on what the bot is doing).

From the logs I see that in your case it was two minutes after that is a long time. I'll try to mitigate this.

Thank you for reporting this.

**Comment by mikeoeo** [comment]
I usually pause it for pvp, since there's no option to select opponent based on TS *cough* *feature request* *cough*, so I wait until it doesn't do anything. Let me know if I can be of any help!

**Comment by ilpersi** [comment]
If you have a feature request, feel free to open a dedicated issue (choose enhancement at creation time). 🙂
