### ISSUE TITLE
Quantity of tokens, shards and badges is recognized wrong

### ISSUE THREAD

**Issue by vatuma** [ilpersi/BHBot#180]
**Describe the bug**
When the bot detects the quantity of tokens, shards and badges it recognizes the numbers wrong (see screenshots)

**To Reproduce**
1. Set resource cost of all activities to 1
2. Run the bot
3 . See logs - some of the numbers are recognized wrong

**Expected behavior**
The numbers in logs should be correct

**Screenshots**
![wrong tokens](https://user-images.githubusercontent.com/914312/95208686-19b98200-07f2-11eb-95ce-b78d150389df.png)
![wrong shards](https://user-images.githubusercontent.com/914312/95208771-3b1a6e00-07f2-11eb-81d5-315fe48aff0f.png)

**Settings**
Please attach a copy of your settings.ini file. Make sure to remove personal/sensitive information

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser, Chromium 69
 - Version 
16:35:21,252 INFO - BHBot v46.2 build on Wed Sep 09 21:46:44 MSK 2020 started.
16:35:21,253 INFO - GIT commit id: 411b3c3d13cf4fbfdc3f172f3e301f42989e9832  time: 2020-09-09T21:39:05+0200

**Comment by vatuma** [comment]
This also applies to PVP tickets and Xeals

**Comment by ilpersi** [comment]
Do you have guild perks that increase the total number of resources?

If you do, make sure to apply the correct max values in settings.ini

Standard configuration (see below) comes without guild perks.

```
# Set maximum resources (For calculating values with guild perks)
maxShards 4
maxTokens 10
maxTickets 10
maxBadges 10
maxXeals 4
```

**Comment by vatuma** [comment]
Ah, that's it! Thank you so much!
