### ISSUE TITLE
Running success rates

### ISSUE THREAD

**Issue by eschwim** [ilpersi/BHBot#66]
We currently log victory/failure in the log output for various activities.  It would be nice if we could keep a running tally (with % success) and print it on every activity completion.  This would give the user immediate feedback as to how well they were doing with their current difficulty settings.

**Comment by ilpersi** [comment]
More in general it would be nice to give more "persistence"  to the BOT. I like statistics as well and they could also be used to set thresholds (i.e. stop the bot after X defeats or similar).

**Comment by Fortigate** [comment]
I've been looking at testing https://github.com/rrd4j/rrd4j to keep a permanent database file for logging activity success rates, item drop rates, TG level etc over time. Any thoughts?

**Comment by ilpersi** [comment]
My idea (and I also have some not so fully functional code) is to use a [SQLite Database](https://github.com/xerial/sqlite-jdbc) to keep this kind of information.

**Comment by eschwim** [comment]
Both have their pros and cons, afaics.  Sqlite will let us have a persistent key/value data store, while RRD will let us store arbitrary key/val pairs and give us all the lovely rdbms goodness, while RRD would let us track long term trends/stats and give us the APIs to do interesting statistical queries, without the disk overhead of storing all of the individual data points.  Why not both? :)

**Comment by eschwim** [comment]
Is there a slack/IRC channel for bhbot? I just registered bhbot.slack.com :)

**Comment by ilpersi** [comment]
We should probably have a discord server :)

**Comment by Fortigate** [comment]
I'm happy for either, simple permanent key/value data is the goal for me, everything on top of that is a bonus. It's certainly not my area of expertise so if other people have working prototypes I'm happy to go with that.

As for a Discord I'm keen on having one, its a little problematic though as there is no privacy so would be easy for people to track account/usernames between BHBot Discord and the official Discord server.

**Comment by EricSpeidel** [comment]
I would second the Slack suggestion, but any type of chat would be much appreciated!

**Comment by ilpersi** [comment]
The original request of keeping track of running success rate is now implemented, so I am closing this.
