### ISSUE TITLE
Pushover msg when >= leg items found

### ISSUE THREAD

**Issue by eschwim** [ilpersi/BHBot#79]
Usually when I check on the bot these days, it is so I can see if it has found any legendary/set items, since the mats they generate are pretty much what drive the entire game.  

It would be nice if I could get a pushover notification when a legendary/set/mythic(hah) item is found, so I can act on it immediately.  We could probably do this by just having a cue that matches that upper left corner of each item level, and filter out legendary materials (e.g. crubble).   It might be hard for raid battles, though, because the victory screen flashes by so quickly.

**Comment by Fortigate** [comment]
Should be pretty easy to implement, instead of scanning and selecting the close button when the victory screen is detected instead scan for legendary/set/mythic item border

**Comment by ilpersi** [comment]
I like the idea and I am also excited to know that someone else besides me is using Pushover notifications! 🤣

**Comment by ilpersi** [comment]
I added the feature in. I wish I could test it and RNG did not help me with that, so let's assume is experimental.

**Comment by Fortigate** [comment]
Any success with this? I've not had any notifications yet. I think that autopilot closes the victory screen automatically in raids so might only work for TG

**Comment by ilpersi** [comment]
I was about to post the same. It looks it is buggy somehow and I have not had enough time to review it.

I was planning to have an internal version that saves the victory pop-up to review them later.
