### ISSUE TITLE
Bot is idle

### ISSUE THREAD

**Issue by reallancelod** [ilpersi/BHBot#88]
Hello there!
I have troubles making the bot work. I've read through many pages already but was unable to find a solution. It was mentioned that this usually occur if my resolution is not good. But i am using 1920x1080 also at 100 dpi.
I ran the init.bat before and did some changes in the settings file.
Do you have any advice for a solution i could try?
Or is that version warning maybe a reason why i run into this problem?
![bot](https://user-images.githubusercontent.com/51834967/59532303-997a5980-8ee8-11e9-9199-2297153048b6.JPG)

**Comment by Fortigate** [comment]
Can you try `force raid` or force dungeon` to see if the bot can start activities manually?

**Comment by reallancelod** [comment]
But nothing more happens. Tried it with dungeons etc. aswell. But no more reaction
![image](https://user-images.githubusercontent.com/51834967/59542609-14526d00-8f07-11e9-9223-c77fe47f7408.png)

**Comment by Fortigate** [comment]
Looks like the bot is running but for some reason it can't take or read screenshots. Do you have admin rights on the account?

**Comment by reallancelod** [comment]
Yea my account have admin rights. It can scroll the game back into center. I try to start the bot as admin,  the window opens up but immediatly close afterwards

**Comment by Fortigate** [comment]
Does `shot` save a screenshot to the screenshot folder?

**Comment by reallancelod** [comment]
Yea, screenshots are possible. But i think we are on the right way. You gave me the idea to check some right restrictions on the files. The java file was partly restricted in access (from windows) and all folders had some restrictions aswell. Not sure if that is intended. But for now i unchecked those restrictions but no further success. It was able to collect dayli reward and closing the news windows. Forcing any other activities are still not possible. Maybe there is something wrong with the settings file? Or does the force action works independent on the file?

**Comment by Fortigate** [comment]
That it can collect dailies and close news is good, that means its working but getting stuck after closing the news. Can you post your settings file (remove any personal info) and I'll test if it works with my bhbot.

Another things you can try is `set raids 7 3 100` then `force raid`

**Comment by reallancelod** [comment]
not sure how i can paste it without formatting, so i linked it as a txt
[settings.txt](https://github.com/Betalord/BHBot/files/3294916/settings.txt)

**Comment by reallancelod** [comment]
How does it sends input to the chromium browser/the game? Maybe somethings blocks the action?

**Comment by Fortigate** [comment]
It uses selenium to automate tasks and send commands, but if it can collect rewards and close the news that means that its fully functional. I just tried your settings file and it ran successfully so I'm lost, maybe try and older version or compiling your own?
