### ISSUE TITLE
Chat server for the bot

### ISSUE THREAD

**Issue by Fortigate** [ilpersi/BHBot#91]
It would be good to have a chat server for the bot for talking about development without clogging up issues, bouncing around ideas and more real time support. 

Discord is not my first option as there is no privacy and it would be easy to track users back to the official server but I'm happy to use an alt account for it as its by far the easiest to set up and manage. Thoughts?

**Comment by EricSpeidel** [comment]
What about gitter[1]? Comes with GitHub integration, so no need to disclose other accounts.

[1]: https://gitter.im/

**Comment by EricSpeidel** [comment]
Looks like a room already exists [here](https://gitter.im/BHBot/community)!

**Comment by ilpersi** [comment]
Telegram can also be an option maybe?
