### ISSUE TITLE
Auto Rune Issue

### ISSUE THREAD

**Issue by KiloChaser** [ilpersi/BHBot#92]
Empty runeset causes loop

https://github.com/ilpersi/BHBot/issues/87

Duplicate, posting for dev notification

**Comment by KiloChaser** [comment]
Update: Even after filling the rune slots the bot is still stuck in a loop [https://i.imgur.com/REvBrV4.png](url)

**Comment by ilpersi** [comment]
What version of the bot are you running? Copy it from the start up log or issue a `print version` command to the bot.

**Comment by KiloChaser** [comment]
v40.1, downloaded the pre-compiled version.

**Comment by Fortigate** [comment]
Likely a mismatch issue again with .isEmpty() and .clear(), I've got some time later to check it out.

**Comment by Fortigate** [comment]
I'm not seeing the same behaviour in the latest version. When I use unknown runes the bot doesn't loop but continues running, then freezes when it tries to start an activity. This is fixed in https://github.com/ilpersi/BHBot/commit/f0001269fb08f13eaa9539d2d0638ad7d2b68872

**Comment by KiloChaser** [comment]
Issue appears to be fixed in v41, thanks! It now checks for runes, fails, then continues running the bot :)
