### ISSUE TITLE
Bot Created WB Lobby But Doesn't Start

### ISSUE THREAD

**Issue by BagOfIce** [ilpersi/BHBot#93]
**Describe the bug**
Bot doesnt start world boss while in lobby.
**To Reproduce**
1. Let bot run 3t3 world boss
2. Bot gets in world boss lobby 
3.World boss lobby fills,
4. Bot proceeds to never start the boss

**Expected behavior**
The bot should click start so that the world boss starts

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chromium
 - Version V41

![bug](https://user-images.githubusercontent.com/49822310/61167101-36331580-a4ee-11e9-9223-ea7b2856acff.png)

**Additional context**
I've already tried reinstalling the bot fresh on a few systems, I dont know if this is just me or the bot running into issues. This also happens if the bot is set to solo the world boss in private, it never clicks start.

**Comment by Fortigate** [comment]
Just released a hotfix that fixes it, can you try that?

**Comment by BagOfIce** [comment]
Thanks for the hotfix. I can  confirm it is now working as intended. Thanks :)
