### ISSUE TITLE
Bot fails to start WB

### ISSUE THREAD

**Issue by mental159** [ilpersi/BHBot#94]
**Describe the bug**
Similar to issue #93, the bot forms a lobby successfully, however once everyone readies, the bot crashes chromium. This does not happen all of the time, but I experience it more frequently than successful runs.

**To Reproduce**
1. Let bot start 3t3 WB
2. Allow lobby to fill
3. Allow all members to ready up
4. Bot crashes

**Expected behavior**
WB should begin and function as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/52889830/61186349-b01be980-a629-11e9-996f-62f6335d9b40.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chromium
 - Version: V41.1

**Additional context**
This issue also happens when the bot attempts to start a WB with no energy. It bring sup the "no energy prompt" and then crashes chromium.

**Comment by BagOfIce** [comment]
I have also had this happen to me even before the bug I submitted. I just didn't care much as for the most part the bot would be able to still do world bosses.

**Comment by mental159** [comment]
Same, the issue is that now with the ability to set preferential order of activities, and the default first priority being WB, the bot can enter a death loop where it loads, attempts a 3t3 WB with no energy, and then crashes. It then restarts and tries WB again with no energy and crashes.

The major pain point is getting caught in this loop while having the required items to conduct other activities. A workaround is obviously to move the priority of WB to the end of the list, but some may not think to do that.

**Comment by ilpersi** [comment]
I've fixed the not enough energy issue for world boss. Right now I am out of energy so I can not test the issue with 3t3rmin4tion lobby.

You can get the new v41.2 version with the not enough energy in the release section.

**Comment by mental159** [comment]
Thanks, I'll grab it and take a look. I'll also report back if I see the other issue occurring after this fix is applied.

**Comment by mental159** [comment]
Confirmed the secondary issue is fixed. I'll monitor for initial issue and report if it is still an issue or not.

**Comment by ilpersi** [comment]
@mental159 
[Here](https://drive.google.com/uc?id=1sTNIzXkSAA-G-vgnwNPBKSe_zogBeOy5&export=download) you can find a compiled version of the bot based on the last commit.

It does not contain any specific fix, the only difference is that, when the "Something went wrong while attempting to start the World Boss, restarting" error happens, a screen will saved in your screenshot folder named "wb-no-start-button_xxxxx".

If this happens again, can you please attach that screen to the issue? Please double check that there are no personal information in it. 😄

**Comment by mental159** [comment]
Sure thing. I have installed it and will monitor for the issue.

I will say I used a +400 energy item to see if I could observe the problem directly and everything worked without an issue after the latest release (not this custom one). However, I will monitor my screenshot folder for that error.

**Comment by ilpersi** [comment]
@mental159 are you still havig issues with the 3xt3r WB? If yes, are you able to provide the "wb-no-start-button_xxxxx" screenshot?

Thank you.

**Comment by mental159** [comment]
I have been monitoring for the issue and have not seen it since the fix for no energy. Either it is rarer than I thought or I confused it for the no energy issue. 

I will close this issue and re-open it if I see it occur again.
