### ISSUE TITLE
Bot Gets Stuck On GVG Team Select Screen

### ISSUE THREAD

**Issue by BagOfIce** [ilpersi/BHBot#95]
**Describe the bug**
Occasionally the bot will get stuck on the screen picking your GVG team.

**To Reproduce**
1. Let bot run
2. Bot selects GVG
3. Then it chooses the default 2nd opponent
4. GVG initiated
5. You see a "DEBUG" GVG start time in console however the bot never clicks accept to start the encounter.

**Expected behavior**
The bot should click the "Accept" button in  order to start the GVG encounter.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium
 - Version V41.1

**Additional context**
This does not occur every time. Every so often it will get stuck on this screen.  I'm not sure how long it can stay like this but so far the last console text was at 10:51 and its now 11:02 with not change, the bot is still stuck on the select GVG team screen.

**Comment by ilpersi** [comment]
After 30 minuts of inactivity the bot will restart itself after producing a crash log and a screenshot of the issue. Are you able to share that? Please double check that there are no personal information shared :)

**Comment by BagOfIce** [comment]
Ciao ilpersi,

I mistakenly clicked start gvg. I'll make sure to provide that information the next time it occurs.

Sorry again,

**Comment by ilpersi** [comment]
@BagOfIce did this happen again? Now that GVG is over it would be difficult for us to reproduce.

**Comment by BagOfIce** [comment]
Nope it did not occur again. although I'm not sure if it's because it has a low likely hood of occurring or the bug fixed actually worked. When GVG comes around again I'll be sure to be on the lookout.

**Comment by ilpersi** [comment]
Ok. I'll close this one then and if it happens again, you can open a new one.
