### ISSUE TITLE
Gets stuck trying to use Superpotion

### ISSUE THREAD

**Issue by Larrush** [ilpersi/BHBot#96]
Sometimes the bot still tries to use the superpotion and then gets stuck. 

![Untitled](https://user-images.githubusercontent.com/47528224/61597751-56608400-ac14-11e9-895a-2c776c8a9dfc.jpg)

```
23:48:16,108 DEBUG - Disabling Ignore Boss
23:48:17,048 DEBUG - Ignore Boss Disabled
23:48:17,062 DEBUG - Ignore Shrine Disabled
23:48:27,777 DEBUG - Seconds since last encounter: 79
23:48:31,588 DEBUG - Seconds since last encounter: 83
23:48:53,900 DEBUG - Slot 3 is up for healing potions, so it does not need revive
23:48:59,772 DEBUG - Slot 4 is up for healing potions, so it does not need revive
23:50:05,039 AUTOREVIVE - Impossible to find the potions button!
23:50:16,226 AUTOREVIVE - Impossible to find the potions button!
23:50:21,753 AUTOREVIVE - Defeat screen, skipping revive check
23:50:30,887 WARN - Raid #1 completed. Result: Defeat.
23:50:30,888 STATS - Raid success rate: .00%
23:50:30,890 STATS - Run time: 7m21s
00:05:21,392 WARN - Idle time exceeded... perhaps caught in a loop? Restarting... (state=Main)
00:05:21,406 WARN - Doing driver emergency restart...
```

This is the log of the last few steps, sadly I didn´t see it happen yet. I always just catch it beeing stuck.

If I find out how this exactly happens I´ll write it here!

**Comment by Larrush** [comment]
![Untitled](https://user-images.githubusercontent.com/47528224/61597860-b0ae1480-ac15-11e9-9edc-215af76f3356.jpg)

Just saw it, so he tries to heal somebody who has still full life and then gets redirectet to this window.
Then trys to use the superpotion, gets confused, reactivates Autopilot.

Btw: 
```
23:40:22,386 INFO - BHBot v41.3 build on Sat Jul 20 21:58:45 CEST 2019 started.
23:40:22,389 INFO - GIT commit id: adf44414af6ae003b1252fab91397a0c8cf202e4  time: 2019-07-20T12:32:56+0200
```
my version should be the newest

**Comment by Fortigate** [comment]
I'm seeing the same issue, I used my super potion to get rid of it but I'll have a look at putting a proper fix in later.

**Comment by ilpersi** [comment]
This is fixed in master branch, I will release a new pr this evening.

**Comment by ilpersi** [comment]
v41.4 is out and it solves this issue.
