### ISSUE TITLE
Can't Run Expedition.

### ISSUE THREAD

**Issue by MWEckert** [ilpersi/BHBot#97]
**Describe the bug**
Continuously opens the expedition screen  and then closes it despite how many badges are available.
04:06:16.275 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:22.277 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:28.322 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:34.288 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:40.288 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:46.278 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:52.254 INFO - Badges: 10, required: >0, Expedition cost: 5
04:06:58.247 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:04.219 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:10.179 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:16.150 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:22.117 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:28.125 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:34.086 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:40.091 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:46.009 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:51.976 INFO - Badges: 10, required: >0, Expedition cost: 5
04:07:57.985 INFO - Badges: -1, required: >0, Expedition cost: 5

**Expected behavior**

I have it set to: expeditions p1 550 25;p2 550 25;p3 550 25;p4 550 25

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 04:44:52.377 INFO - User command: <print version>
04:44:52.380 INFO - BHBot v39.1 build on Sat May 18 05:02:54 MDT 2019 started.
04:44:52.382 INFO - GIT commit id: f027690bf7109224fd0c9218fb6d1fc1de96fa85  time: 2019-05-14T17:09:16+0200

**Additional context**
It was running GvG fine, refused to run expedition, even after update.

**Comment by Fortigate** [comment]
This was a big with the new resource management in v39, one of the latest v41 builds on the [releases](https://github.com/ilpersi/BHBot/releases) page will fix it.

**Comment by ilpersi** [comment]
@MWEckert are you having the same issue with the latest version of BHBot?

**Comment by MWEckert** [comment]
I got it updated properly and havent had an issue since. Thanks!
