### ISSUE TITLE
Gauntlet stuck on level 60

### ISSUE THREAD

**Issue by Larrush** [ilpersi/BHBot#98]
The bot runs on level 60 even though I have set it way higher.
I have the newest master with the decrease feature, so there might be some issue.

Or maybe it´s just me again ^^

```
# Trials/Gauntlet difficulty level
difficultyGauntlet 885
difficultyTrials 890
# Decrease difficulty when you loose
# format: <dungeon_type>:<levels_to_decrease>
# Only Trials and Gauntlet supported, you can mix them as you want (t=trials, g=gauntlet)
# Example 'difficultyFailsafe t:1 g:5' -> you loose a trial, difficultyTrials is decreased by 1. you loose a gauntlet, difficultyGauntlet is decreased by 5
difficultyFailsafe t:1 g:1
```

**Comment by ilpersi** [comment]
Can you please paste the version info that you get with `print version`?

**Comment by Larrush** [comment]
11:55:59,964 ERROR - Impossile to process user command: print
 java.lang.ArrayIndexOutOfBoundsException: 1
        at BHBot.processCommand(BHBot.java:316) ~[BHBot.jar:?]
        at BHBot.main(BHBot.java:147) [BHBot.jar:?]

Sadly I only get this message. 
I redownloaded the .jar and it still shows me this

**Comment by ilpersi** [comment]
The command to type is `print version` not just `print`.

**Comment by Larrush** [comment]
```
21:56:55,175 INFO - BHBot v41.5 build on Wed Aug 07 11:55:33 CEST 2019 started.
21:56:55,176 INFO - GIT commit id: 6acd46cf2b6cea6ea37c36fcada82a09e5521990  time: 2019-07-31T20:14:12+0200
```

I´ll try to redownload it later, maybe I compiled something wrong

**Comment by ilpersi** [comment]
> 22:09:30,757 INFO - GIT commit id: 6acd46cf2b6cea6ea37c36fcada82a09e5521990  time: 2019-07-31T20:14:12+0200

This means, you are using version from commit https://github.com/ilpersi/BHBot/commit/6acd46cf2b6cea6ea37c36fcada82a09e5521990 that is dated July 31 so before the new feature has been released.

What is happening is that you are using an old code base (dated July 31) with a new ini settings. As the old code base does not find the `difficulty` as a fail-safe it is applying the default value that is 60. Make sure to compile the latest version and try again.
